#!/bin/sh
#
# @name fr
#
# @type Quadrotor Wide
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# 
#
#
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	# TODO tune roll/pitch separately
	param set MC_ROLL_P 1.5
	param set MC_ROLLRATE_P 0.15
	param set MC_ROLLRATE_I 0.03
	param set MC_ROLLRATE_D 0.030
	param set MC_PITCH_P 5
	param set MC_PITCHRATE_P 0.2
	param set MC_PITCHRATE_I 0.03
	param set MC_PITCHRATE_D 0.03
	param set MC_YAW_P 2
	param set MC_YAWRATE_P 0.1
	param set MC_YAWRATE_I 0.25
	param set MC_YAWRATE_D 0

	param set BAT_V_DIV 12.27559
fi

set MIXER quad_w
set MIXER_AUX pass

set PWM_OUT 12345678
