#!/bin/sh
#
# @name QUAD_TILTROTOR
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @output AUX1 servo motor for rotor 1 arm ---right
# @output AUX2 servo motor for rotor 3 arm ---left
# @output AUX3 servo motor for rotor 4 arm ---right
# @output AUX4 servo motor for rotor 2 arm ---left
#
#
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	# TODO tune roll/pitch separately

        param set CBRK_AIRSPD_CHK 162128

	param set FW_ARSP_MODE 2

	param set FW_L1_PERIOD 17
	param set FW_MAN_R_MAX 50
	param set FW_ACRO_X_MAX   270
	param set FW_ACRO_Y_MAX   270
	param set FW_ACRO_Z_MAX   180
	param set FW_PR_FF    0.5
	param set FW_PR_P 0.08
	param set FW_PSP_OFF  5
	param set FW_P_LIM_MAX    30
	param set FW_P_LIM_MIN    -30
	param set FW_P_RMAX_NEG   60
	param set FW_P_RMAX_POS   60
	param set FW_RR_FF    0.33
	param set FW_RR_P 0.11
	param set FW_YR_FF    0.3
	param set FW_YR_P 0.05

	param set MC_ROLL_P 3.2
	param set MC_ROLLRATE_P 0.138
	param set MC_ROLLRATE_I 0.03
	param set MC_ROLLRATE_D 0.00
	param set MC_PITCH_P 4.0
	param set MC_PITCHRATE_P 0.39
	param set MC_PITCHRATE_I 0.1
	param set MC_PITCHRATE_D 0.005
	param set MC_YAW_P 1.5
	param set MC_YAWRATE_P 0.28
	param set MC_YAWRATE_I 0.25
	param set MC_YAWRATE_D 0

	param set BAT_V_DIV 12.27559

        param set PWM_RATE 400



        param set PWM_AUX_RATE 50
        param set PWM_MAIN_MIN1 1130
        param set PWM_MAIN_MIN2 1150
        param set PWM_MAIN_MAX1 1940
        param set PWM_MAIN_MAX2 1920

	param set PWM_MAIN_MIN3 1000
        param set PWM_MAIN_MIN4 1246
        param set PWM_MAIN_MAX3 1741
        param set PWM_MAIN_MAX4 2000

        param set PWM_MAIN_MIN1 1000
        param set PWM_MAIN_MIN2 1000
        param set PWM_MAIN_MAX1 1400
        param set PWM_MAIN_MAX2 1400

	param set PWM_MAIN_MIN3 1000
        param set PWM_MAIN_MIN4 1000
        param set PWM_MAIN_MAX3 1400
        param set PWM_MAIN_MAX4 1400

        # param set PWM_MAIN_MIN5 1000
        # param set PWM_MAIN_MIN6 850
        # param set PWM_MAIN_MAX5 2150
        # param set PWM_MAIN_MAX6 1850

	# param set PWM_MAIN_MIN7 1000
        # param set PWM_MAIN_MIN8 850
        # param set PWM_MAIN_MAX7 2150
        # param set PWM_MAIN_MAX8 1850


	param set VT_B_TRANS_DUR  1
	param set VT_F_TRANS_DUR  1.2
	param set VT_F_TR_OL_TM   2
	param set VT_FW_DIFTHR_EN 1
	param set VT_FW_DIFTHR_SC 0.17
	param set VT_FW_PERM_STAB 0
	param set VT_IDLE_PWM_MC 1120
        param set VT_FW_MOT_OFFID 5678
	param set VT_MOT_ID 5678
	param set VT_TILT_FW  0.67
	param set VT_TILT_MC  0
	param set VT_TILT_TRANS   0.4
	param set VT_TRANS_MIN_TM 1.2
	param set VT_TRANS_P2_DUR 1.3
	param set VT_ELEV_MC_LOCK 1
	param set VT_TYPE 1
fi

set MAV_TYPE 21
set MIXER quad_tilt
set MIXER_AUX quad_tiltt

set PWM_OUT 12345678
set PWM_AUX_OUT 1234
