#!/bin/sh
#
# @name VTOL Tiltrotor
#
# @type VTOL Tiltrotor
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MAX 25
	param set FW_AIRSPD_MIN 14
	param set FW_AIRSPD_TRIM 16

	param set MC_PITCHRATE_D 0.004
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCHRATE_MAX 1200
	param set MC_PITCHRATE_P 0.343
	param set MC_PITCH_P 4.3
	param set MC_ROLLRATE_D 0.003
	param set MC_ROLLRATE_I 0.05
	param set MC_ROLLRATE_MAX 1200
	param set MC_ROLLRATE_P 0.14
	param set MC_ROLL_P 4.0
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_MAX 600
	param set MC_YAWRATE_P 0.18
	param set MC_YAW_P 1

	param set MIS_LTRMIN_ALT 10
	param set MIS_TAKEOFF_ALT 10
	param set MIS_YAW_TMT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_HOR_MAX 2
	param set MPC_THR_MIN 0.1
	param set MPC_TKO_SPEED 1
	param set MPC_XY_P 0.15
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.05
	param set MPC_Z_VEL_MAX_DN 1.5
	param set MPC_Z_VEL_P 0.8

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_B_TRANS_DUR  1
	param set VT_F_TRANS_DUR  1.2
	param set VT_F_TR_OL_TM   4
	param set VT_FW_DIFTHR_EN 1
	param set VT_FW_DIFTHR_SC 0.17
	param set VT_FW_PERM_STAB 0
	param set VT_IDLE_PWM_MC 1130
	param set VT_MOT_ID 1234
	param set VT_TILT_FW  1
	param set VT_TILT_MC  0
	param set VT_TILT_TRANS   0.4
	param set VT_TRANS_MIN_TM 1.2
	param set VT_TRANS_P2_DUR 1.3
	param set VT_ELEV_MC_LOCK 1
	param set VT_TYPE 1

fi

set MAV_TYPE 21

set MIXER_FILE etc/mixers-sitl/ffff_w_sitl.main.mix
set MIXER custom
